swagger: "2.0"
info:
  title: "Sign In tracker API"
  # description: ""
  version: 1.0.0

# host: api.example.com
# basePath: /v1
schemes:
  # - https
  - http

consumes:
  - application/json

produces:
  - application/json

paths:
  /students:
    get:
      summary: Returns a collection of students
      description: Collection of students registered in the sign in tracker.
                   By default only @meta.id's are returned in the colleciton. The
                   links can be expanded if desired. 
      tags:
        - Students
      parameters:
      - in: query
        name: expand  
        type: boolean
        default: true
        description: Expand the links
      responses:
        200:
          description: A array of User objects
          schema:
            type: object
            properties:
              "@meta.id":
                $ref: "#/definitions/id"
              Members:
                type: array
                items:
                  allOf:
                  - $ref: "#/definitions/idRef"
                  - $ref: "#/definitions/Student"
            required:
              - Members
              - "@meta.id"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Create a new student
      tags:
        - Students
      parameters:
      - in: body
        name: student
        schema:
          $ref: "#/definitions/Student"
      responses:
        201:
          description: Student successfully created
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /students/{id}:
    get:
      summary: Get a particular student
      tags:
        - Students
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Student response
          schema:
            $ref: "#/definitions/Student"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete the student with the given ID
      tags:
        - Students
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Representation of the student that was just deleted.
          schema:
            $ref: "#/definitions/Student"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Update a particular student
      tags:
        - Students
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - in: body
        name: student
        schema:
          $ref: "#/definitions/Student"
      responses:
        200:
          description: Updated student response
          schema:
            $ref: "#/definitions/Student"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /mentors:
    get:
      summary: Returns a collection of mentors
      description: Collection of mentors registered in the sign in tracker.
                   By default only @meta.id's are returned in the colleciton. The
                   links can be expanded if desired. 
      tags:
        - Mentors
      parameters:
      - in: query
        name: expand  
        type: boolean
        default: true
        description: Expand the links
      responses:
        200:
          description: A array of mentor objects
          schema:
            type: object
            properties:
              "@meta.id":
                $ref: "#/definitions/id"
              Members:
                type: array
                items:
                  allOf:
                  - $ref: "#/definitions/idRef"
                  - $ref: "#/definitions/Mentor"
            required:
              - Members
              - "@meta.id"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Create a new mentor
      tags:
        - Mentors

      parameters:
      - in: body
        name: mentor
        schema:
          $ref: "#/definitions/Mentor"
      responses:
        201:
          description: Mentor successfully created
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /mentors/{id}:
    get:
      summary: Get a particular mentor
      tags:
        - Mentors

      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Mentor response
          schema:
            $ref: "#/definitions/Mentor"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete the mentor with the given ID
      tags:
        - Mentors

      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Representation of the mentor that was just deleted.
          schema:
            $ref: "#/definitions/Mentor"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Update a particular mentor
      tags:
        - Mentors
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - in: body
        name: mentor
        schema:
          $ref: "#/definitions/Mentor"
          
      responses:
        200:
          description: Updated mentor response
          schema:
            $ref: "#/definitions/Mentor"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /meetings:
    get:
      summary: Returns a collection of Meetings
      description: Collection of meetings registered in the sign in tracker.
                   By default only @meta.id's are returned in the colleciton. The
                   links can be expanded if desired. 
      tags:
        - Meetings
      parameters:
      - in: query
        name: expand  
        type: boolean
        default: true
        description: Expand the links
      responses:
        200:
          description: A array of meeting objects
          schema:
            type: object
            properties:
              "@meta.id":
                $ref: "#/definitions/id"
              Members:
                type: array
                items:
                  allOf:
                  - $ref: "#/definitions/idRef"
                  - $ref: "#/definitions/Meeting"
            required:
              - Members
              - "@meta.id"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    post:
      summary: Create a new meeting
      tags:
        - Meetings

      parameters:
      - in: body
        name: meeting
        schema:
          $ref: "#/definitions/Meeting"
      responses:
        201:
          description: Meeting successfully created
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /meetings/{id}:
    get:
      summary: Get a particular meeting
      tags:
        - Meetings

      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Meeting response
          schema:
            $ref: "#/definitions/Meeting"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    delete:
      summary: Delete the meeting with the given ID
      tags:
        - Meetings

      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Representation of the meeting that was just deleted.
          schema:
            $ref: "#/definitions/Meeting"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"
    patch:
      summary: Update a particular meeting
      tags:
        - Meetings
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - in: body
        name: meeting
        schema:
          $ref: "#/definitions/Meeting"
      responses:
        200:
          description: Updated meeting response
          schema:
            $ref: "#/definitions/Meeting"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/Error"

  /meetings/{id}/committed:
    # List of Students or mentors who committed to showing up


definitions:
  Student:
    type: object
    properties:
      # "@meta.id":
      #   $ref: "#/definitions/id"
      id:
        type: string
        example: abc123
      schoolId:
        type: string
        example: sjost150
      name:
        type: object
        properties:
          first:
            type: string
            example: Ryan
          last:
            type: string
            example: Sjostrand
        required:
          - first
          - last
      graduationYear:
        type: integer
        example: 2015
    required:
      # - "@meta.id"
      - name
      - id

  Mentor:
    type: object
    properties:
      # "@meta.id":
      #   $ref: "#/definitions/id"
      id:
        type: string
        example: abc123
      name:
        type: object
        properties:
          first:
            type: string
            example: Ryan
          last:
            type: string
            example: Sjostrand
        required:
          - first
          - last
    required:
      # - "@meta.id"
      - name
      - id

  Meeting:
    type: object
    properties:
      id:
        type: string
      Day:
        type: string
        format: date
      StartTime:
        $ref: "#/definitions/Time"
      EndTime:
        $ref: "#/definitions/Time"

  Day:
    type: object
    properties:
      Year:
        type: integer
      Month:
        type: integer
        minimum: 1
        maximum: 12
      Day:
        type: integer
        minimum: 1
        maximum: 31

  Time:
    type: object
    properties:
      "Hour":
        type: integer
        minimum: 0
        maximum: 24
      "Minute":
        type: integer
        minimum: 0
        maximum: 59
      # "Second":
      #   type: integer
      #   default: 0
      #   minimum: 0
      #   maximum: 59
    required:
      - Hour
      - Minute


  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string



  # These meta tags have been influenced after the OData spec
  # Based/Influenced from: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml
  count:
    description: The number of items in a collection.
    readOnly: true
    type: integer

  id:
    description: The unique identifier for a resource.
    format: uri-reference
    readOnly: true
    type: string
    example: "foo"

  idRef:
    additionalProperties: false
    description: A reference to a resource.
    properties:
      '@meta.id':
        $ref: '#/definitions/id'
    type: object
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /signin/1.0