// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// DeleteMeetingsIDNoContentCode is the HTTP code returned for type DeleteMeetingsIDNoContent
const DeleteMeetingsIDNoContentCode int = 204

/*DeleteMeetingsIDNoContent Representation of the meeting that was just deleted.

swagger:response deleteMeetingsIdNoContent
*/
type DeleteMeetingsIDNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Meeting `json:"body,omitempty"`
}

// NewDeleteMeetingsIDNoContent creates DeleteMeetingsIDNoContent with default headers values
func NewDeleteMeetingsIDNoContent() *DeleteMeetingsIDNoContent {

	return &DeleteMeetingsIDNoContent{}
}

// WithPayload adds the payload to the delete meetings Id no content response
func (o *DeleteMeetingsIDNoContent) WithPayload(payload *models.Meeting) *DeleteMeetingsIDNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete meetings Id no content response
func (o *DeleteMeetingsIDNoContent) SetPayload(payload *models.Meeting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMeetingsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteMeetingsIDDefault Unexpected error

swagger:response deleteMeetingsIdDefault
*/
type DeleteMeetingsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteMeetingsIDDefault creates DeleteMeetingsIDDefault with default headers values
func NewDeleteMeetingsIDDefault(code int) *DeleteMeetingsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteMeetingsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete meetings ID default response
func (o *DeleteMeetingsIDDefault) WithStatusCode(code int) *DeleteMeetingsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete meetings ID default response
func (o *DeleteMeetingsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete meetings ID default response
func (o *DeleteMeetingsIDDefault) WithPayload(payload *models.Error) *DeleteMeetingsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete meetings ID default response
func (o *DeleteMeetingsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMeetingsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
