// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetMeetingsURL generates an URL for the get meetings operation
type GetMeetingsURL struct {
	AfterDate  *strfmt.Date
	BeforeDate *strfmt.Date
	Expand     *bool
	Teamid     *int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetMeetingsURL) WithBasePath(bp string) *GetMeetingsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetMeetingsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetMeetingsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/meetings"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var afterDate string
	if o.AfterDate != nil {
		afterDate = o.AfterDate.String()
	}
	if afterDate != "" {
		qs.Set("afterDate", afterDate)
	}

	var beforeDate string
	if o.BeforeDate != nil {
		beforeDate = o.BeforeDate.String()
	}
	if beforeDate != "" {
		qs.Set("beforeDate", beforeDate)
	}

	var expand string
	if o.Expand != nil {
		expand = swag.FormatBool(*o.Expand)
	}
	if expand != "" {
		qs.Set("expand", expand)
	}

	var teamid string
	if o.Teamid != nil {
		teamid = swag.FormatInt64(*o.Teamid)
	}
	if teamid != "" {
		qs.Set("teamid", teamid)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetMeetingsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetMeetingsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetMeetingsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetMeetingsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetMeetingsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetMeetingsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
