// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetMeetingsIDHandlerFunc turns a function with the right signature into a get meetings ID handler
type GetMeetingsIDHandlerFunc func(GetMeetingsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetMeetingsIDHandlerFunc) Handle(params GetMeetingsIDParams) middleware.Responder {
	return fn(params)
}

// GetMeetingsIDHandler interface for that can handle valid get meetings ID params
type GetMeetingsIDHandler interface {
	Handle(GetMeetingsIDParams) middleware.Responder
}

// NewGetMeetingsID creates a new http.Handler for the get meetings ID operation
func NewGetMeetingsID(ctx *middleware.Context, handler GetMeetingsIDHandler) *GetMeetingsID {
	return &GetMeetingsID{Context: ctx, Handler: handler}
}

/*GetMeetingsID swagger:route GET /meetings/{id} Meetings getMeetingsId

Get a particular meeting

*/
type GetMeetingsID struct {
	Context *middleware.Context
	Handler GetMeetingsIDHandler
}

func (o *GetMeetingsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetMeetingsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
