// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetMeetingsOKCode is the HTTP code returned for type GetMeetingsOK
const GetMeetingsOKCode int = 200

/*GetMeetingsOK A array of meeting objects

swagger:response getMeetingsOK
*/
type GetMeetingsOK struct {

	/*
	  In: Body
	*/
	Payload *GetMeetingsOKBody `json:"body,omitempty"`
}

// NewGetMeetingsOK creates GetMeetingsOK with default headers values
func NewGetMeetingsOK() *GetMeetingsOK {

	return &GetMeetingsOK{}
}

// WithPayload adds the payload to the get meetings o k response
func (o *GetMeetingsOK) WithPayload(payload *GetMeetingsOKBody) *GetMeetingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetings o k response
func (o *GetMeetingsOK) SetPayload(payload *GetMeetingsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetMeetingsDefault Unexpected error

swagger:response getMeetingsDefault
*/
type GetMeetingsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetingsDefault creates GetMeetingsDefault with default headers values
func NewGetMeetingsDefault(code int) *GetMeetingsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMeetingsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get meetings default response
func (o *GetMeetingsDefault) WithStatusCode(code int) *GetMeetingsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get meetings default response
func (o *GetMeetingsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get meetings default response
func (o *GetMeetingsDefault) WithPayload(payload *models.Error) *GetMeetingsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetings default response
func (o *GetMeetingsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetingsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
