// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetMeetingsIDOKCode is the HTTP code returned for type GetMeetingsIDOK
const GetMeetingsIDOKCode int = 200

/*GetMeetingsIDOK Meeting response

swagger:response getMeetingsIdOK
*/
type GetMeetingsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Meeting `json:"body,omitempty"`
}

// NewGetMeetingsIDOK creates GetMeetingsIDOK with default headers values
func NewGetMeetingsIDOK() *GetMeetingsIDOK {

	return &GetMeetingsIDOK{}
}

// WithPayload adds the payload to the get meetings Id o k response
func (o *GetMeetingsIDOK) WithPayload(payload *models.Meeting) *GetMeetingsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetings Id o k response
func (o *GetMeetingsIDOK) SetPayload(payload *models.Meeting) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetingsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetMeetingsIDDefault Unexpected error

swagger:response getMeetingsIdDefault
*/
type GetMeetingsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetMeetingsIDDefault creates GetMeetingsIDDefault with default headers values
func NewGetMeetingsIDDefault(code int) *GetMeetingsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetMeetingsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get meetings ID default response
func (o *GetMeetingsIDDefault) WithStatusCode(code int) *GetMeetingsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get meetings ID default response
func (o *GetMeetingsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get meetings ID default response
func (o *GetMeetingsIDDefault) WithPayload(payload *models.Error) *GetMeetingsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get meetings ID default response
func (o *GetMeetingsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetMeetingsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
