// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchMeetingsIDHandlerFunc turns a function with the right signature into a patch meetings ID handler
type PatchMeetingsIDHandlerFunc func(PatchMeetingsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchMeetingsIDHandlerFunc) Handle(params PatchMeetingsIDParams) middleware.Responder {
	return fn(params)
}

// PatchMeetingsIDHandler interface for that can handle valid patch meetings ID params
type PatchMeetingsIDHandler interface {
	Handle(PatchMeetingsIDParams) middleware.Responder
}

// NewPatchMeetingsID creates a new http.Handler for the patch meetings ID operation
func NewPatchMeetingsID(ctx *middleware.Context, handler PatchMeetingsIDHandler) *PatchMeetingsID {
	return &PatchMeetingsID{Context: ctx, Handler: handler}
}

/*PatchMeetingsID swagger:route PATCH /meetings/{id} Meetings patchMeetingsId

Update a particular meeting

*/
type PatchMeetingsID struct {
	Context *middleware.Context
	Handler PatchMeetingsIDHandler
}

func (o *PatchMeetingsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchMeetingsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
