// Code generated by go-swagger; DO NOT EDIT.

package meetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostMeetingsHandlerFunc turns a function with the right signature into a post meetings handler
type PostMeetingsHandlerFunc func(PostMeetingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMeetingsHandlerFunc) Handle(params PostMeetingsParams) middleware.Responder {
	return fn(params)
}

// PostMeetingsHandler interface for that can handle valid post meetings params
type PostMeetingsHandler interface {
	Handle(PostMeetingsParams) middleware.Responder
}

// NewPostMeetings creates a new http.Handler for the post meetings operation
func NewPostMeetings(ctx *middleware.Context, handler PostMeetingsHandler) *PostMeetings {
	return &PostMeetings{Context: ctx, Handler: handler}
}

/*PostMeetings swagger:route POST /meetings Meetings postMeetings

Create a new meeting

*/
type PostMeetings struct {
	Context *middleware.Context
	Handler PostMeetingsHandler
}

func (o *PostMeetings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostMeetingsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
