// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// DeletePeopleIDNoContentCode is the HTTP code returned for type DeletePeopleIDNoContent
const DeletePeopleIDNoContentCode int = 204

/*DeletePeopleIDNoContent Representation of the person that was just deleted.

swagger:response deletePeopleIdNoContent
*/
type DeletePeopleIDNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Person `json:"body,omitempty"`
}

// NewDeletePeopleIDNoContent creates DeletePeopleIDNoContent with default headers values
func NewDeletePeopleIDNoContent() *DeletePeopleIDNoContent {

	return &DeletePeopleIDNoContent{}
}

// WithPayload adds the payload to the delete people Id no content response
func (o *DeletePeopleIDNoContent) WithPayload(payload *models.Person) *DeletePeopleIDNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete people Id no content response
func (o *DeletePeopleIDNoContent) SetPayload(payload *models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePeopleIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeletePeopleIDDefault Unexpected error

swagger:response deletePeopleIdDefault
*/
type DeletePeopleIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeletePeopleIDDefault creates DeletePeopleIDDefault with default headers values
func NewDeletePeopleIDDefault(code int) *DeletePeopleIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeletePeopleIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete people ID default response
func (o *DeletePeopleIDDefault) WithStatusCode(code int) *DeletePeopleIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete people ID default response
func (o *DeletePeopleIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete people ID default response
func (o *DeletePeopleIDDefault) WithPayload(payload *models.Error) *DeletePeopleIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete people ID default response
func (o *DeletePeopleIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeletePeopleIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
