// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePeopleIDHandlerFunc turns a function with the right signature into a delete people ID handler
type DeletePeopleIDHandlerFunc func(DeletePeopleIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePeopleIDHandlerFunc) Handle(params DeletePeopleIDParams) middleware.Responder {
	return fn(params)
}

// DeletePeopleIDHandler interface for that can handle valid delete people ID params
type DeletePeopleIDHandler interface {
	Handle(DeletePeopleIDParams) middleware.Responder
}

// NewDeletePeopleID creates a new http.Handler for the delete people ID operation
func NewDeletePeopleID(ctx *middleware.Context, handler DeletePeopleIDHandler) *DeletePeopleID {
	return &DeletePeopleID{Context: ctx, Handler: handler}
}

/*DeletePeopleID swagger:route DELETE /people/{id} People deletePeopleId

Delete the person with the given ID

*/
type DeletePeopleID struct {
	Context *middleware.Context
	Handler DeletePeopleIDHandler
}

func (o *DeletePeopleID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePeopleIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
