// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetPeopleOKCode is the HTTP code returned for type GetPeopleOK
const GetPeopleOKCode int = 200

/*GetPeopleOK A array of User objects

swagger:response getPeopleOK
*/
type GetPeopleOK struct {

	/*
	  In: Body
	*/
	Payload *GetPeopleOKBody `json:"body,omitempty"`
}

// NewGetPeopleOK creates GetPeopleOK with default headers values
func NewGetPeopleOK() *GetPeopleOK {

	return &GetPeopleOK{}
}

// WithPayload adds the payload to the get people o k response
func (o *GetPeopleOK) WithPayload(payload *GetPeopleOKBody) *GetPeopleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people o k response
func (o *GetPeopleOK) SetPayload(payload *GetPeopleOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPeopleDefault Unexpected error

swagger:response getPeopleDefault
*/
type GetPeopleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPeopleDefault creates GetPeopleDefault with default headers values
func NewGetPeopleDefault(code int) *GetPeopleDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPeopleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get people default response
func (o *GetPeopleDefault) WithStatusCode(code int) *GetPeopleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get people default response
func (o *GetPeopleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get people default response
func (o *GetPeopleDefault) WithPayload(payload *models.Error) *GetPeopleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people default response
func (o *GetPeopleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
