// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"

	models "signin2/models"
)

// GetPeopleHandlerFunc turns a function with the right signature into a get people handler
type GetPeopleHandlerFunc func(GetPeopleParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPeopleHandlerFunc) Handle(params GetPeopleParams) middleware.Responder {
	return fn(params)
}

// GetPeopleHandler interface for that can handle valid get people params
type GetPeopleHandler interface {
	Handle(GetPeopleParams) middleware.Responder
}

// NewGetPeople creates a new http.Handler for the get people operation
func NewGetPeople(ctx *middleware.Context, handler GetPeopleHandler) *GetPeople {
	return &GetPeople{Context: ctx, Handler: handler}
}

/*GetPeople swagger:route GET /people People getPeople

Returns a collection of people

Collection of people registered in the sign in tracker. By default only @meta.id's are returned in the colleciton. The links can be expanded if desired.

*/
type GetPeople struct {
	Context *middleware.Context
	Handler GetPeopleHandler
}

func (o *GetPeople) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPeopleParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetPeopleOKBody get people o k body
// swagger:model GetPeopleOKBody
type GetPeopleOKBody struct {

	// at meta id
	// Required: true
	AtMetaID models.ID `json:"@meta.id"`

	// members
	// Required: true
	Members []*models.Person `json:"Members"`
}

// Validate validates this get people o k body
func (o *GetPeopleOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAtMetaID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMembers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetPeopleOKBody) validateAtMetaID(formats strfmt.Registry) error {

	if err := o.AtMetaID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("getPeopleOK" + "." + "@meta.id")
		}
		return err
	}

	return nil
}

func (o *GetPeopleOKBody) validateMembers(formats strfmt.Registry) error {

	if err := validate.Required("getPeopleOK"+"."+"Members", "body", o.Members); err != nil {
		return err
	}

	for i := 0; i < len(o.Members); i++ {
		if swag.IsZero(o.Members[i]) { // not required
			continue
		}

		if o.Members[i] != nil {
			if err := o.Members[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getPeopleOK" + "." + "Members" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetPeopleOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPeopleOKBody) UnmarshalBinary(b []byte) error {
	var res GetPeopleOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
