// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetPeopleIDOKCode is the HTTP code returned for type GetPeopleIDOK
const GetPeopleIDOKCode int = 200

/*GetPeopleIDOK Person response

swagger:response getPeopleIdOK
*/
type GetPeopleIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Person `json:"body,omitempty"`
}

// NewGetPeopleIDOK creates GetPeopleIDOK with default headers values
func NewGetPeopleIDOK() *GetPeopleIDOK {

	return &GetPeopleIDOK{}
}

// WithPayload adds the payload to the get people Id o k response
func (o *GetPeopleIDOK) WithPayload(payload *models.Person) *GetPeopleIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people Id o k response
func (o *GetPeopleIDOK) SetPayload(payload *models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPeopleIDDefault Unexpected error

swagger:response getPeopleIdDefault
*/
type GetPeopleIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPeopleIDDefault creates GetPeopleIDDefault with default headers values
func NewGetPeopleIDDefault(code int) *GetPeopleIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPeopleIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get people ID default response
func (o *GetPeopleIDDefault) WithStatusCode(code int) *GetPeopleIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get people ID default response
func (o *GetPeopleIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get people ID default response
func (o *GetPeopleIDDefault) WithPayload(payload *models.Error) *GetPeopleIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get people ID default response
func (o *GetPeopleIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPeopleIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
