// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PatchPeopleIDOKCode is the HTTP code returned for type PatchPeopleIDOK
const PatchPeopleIDOKCode int = 200

/*PatchPeopleIDOK Updated student response

swagger:response patchPeopleIdOK
*/
type PatchPeopleIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Person `json:"body,omitempty"`
}

// NewPatchPeopleIDOK creates PatchPeopleIDOK with default headers values
func NewPatchPeopleIDOK() *PatchPeopleIDOK {

	return &PatchPeopleIDOK{}
}

// WithPayload adds the payload to the patch people Id o k response
func (o *PatchPeopleIDOK) WithPayload(payload *models.Person) *PatchPeopleIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch people Id o k response
func (o *PatchPeopleIDOK) SetPayload(payload *models.Person) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchPeopleIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchPeopleIDDefault Unexpected error

swagger:response patchPeopleIdDefault
*/
type PatchPeopleIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchPeopleIDDefault creates PatchPeopleIDDefault with default headers values
func NewPatchPeopleIDDefault(code int) *PatchPeopleIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchPeopleIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch people ID default response
func (o *PatchPeopleIDDefault) WithStatusCode(code int) *PatchPeopleIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch people ID default response
func (o *PatchPeopleIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch people ID default response
func (o *PatchPeopleIDDefault) WithPayload(payload *models.Error) *PatchPeopleIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch people ID default response
func (o *PatchPeopleIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchPeopleIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
