// Code generated by go-swagger; DO NOT EDIT.

package people

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PostPeopleCreatedCode is the HTTP code returned for type PostPeopleCreated
const PostPeopleCreatedCode int = 201

/*PostPeopleCreated Person successfully created

swagger:response postPeopleCreated
*/
type PostPeopleCreated struct {
}

// NewPostPeopleCreated creates PostPeopleCreated with default headers values
func NewPostPeopleCreated() *PostPeopleCreated {

	return &PostPeopleCreated{}
}

// WriteResponse to the client
func (o *PostPeopleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*PostPeopleDefault Unexpected error

swagger:response postPeopleDefault
*/
type PostPeopleDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostPeopleDefault creates PostPeopleDefault with default headers values
func NewPostPeopleDefault(code int) *PostPeopleDefault {
	if code <= 0 {
		code = 500
	}

	return &PostPeopleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post people default response
func (o *PostPeopleDefault) WithStatusCode(code int) *PostPeopleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post people default response
func (o *PostPeopleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post people default response
func (o *PostPeopleDefault) WithPayload(payload *models.Error) *PostPeopleDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post people default response
func (o *PostPeopleDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostPeopleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
