// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// DeleteStudentsIDNoContentCode is the HTTP code returned for type DeleteStudentsIDNoContent
const DeleteStudentsIDNoContentCode int = 204

/*DeleteStudentsIDNoContent Representation of the student that was just deleted.

swagger:response deleteStudentsIdNoContent
*/
type DeleteStudentsIDNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Student `json:"body,omitempty"`
}

// NewDeleteStudentsIDNoContent creates DeleteStudentsIDNoContent with default headers values
func NewDeleteStudentsIDNoContent() *DeleteStudentsIDNoContent {

	return &DeleteStudentsIDNoContent{}
}

// WithPayload adds the payload to the delete students Id no content response
func (o *DeleteStudentsIDNoContent) WithPayload(payload *models.Student) *DeleteStudentsIDNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete students Id no content response
func (o *DeleteStudentsIDNoContent) SetPayload(payload *models.Student) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteStudentsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteStudentsIDDefault Unexpected error

swagger:response deleteStudentsIdDefault
*/
type DeleteStudentsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteStudentsIDDefault creates DeleteStudentsIDDefault with default headers values
func NewDeleteStudentsIDDefault(code int) *DeleteStudentsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteStudentsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete students ID default response
func (o *DeleteStudentsIDDefault) WithStatusCode(code int) *DeleteStudentsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete students ID default response
func (o *DeleteStudentsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete students ID default response
func (o *DeleteStudentsIDDefault) WithPayload(payload *models.Error) *DeleteStudentsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete students ID default response
func (o *DeleteStudentsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteStudentsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
