// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteStudentsIDHandlerFunc turns a function with the right signature into a delete students ID handler
type DeleteStudentsIDHandlerFunc func(DeleteStudentsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteStudentsIDHandlerFunc) Handle(params DeleteStudentsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteStudentsIDHandler interface for that can handle valid delete students ID params
type DeleteStudentsIDHandler interface {
	Handle(DeleteStudentsIDParams) middleware.Responder
}

// NewDeleteStudentsID creates a new http.Handler for the delete students ID operation
func NewDeleteStudentsID(ctx *middleware.Context, handler DeleteStudentsIDHandler) *DeleteStudentsID {
	return &DeleteStudentsID{Context: ctx, Handler: handler}
}

/*DeleteStudentsID swagger:route DELETE /students/{id} deleteStudentsId

Delete the student with the given ID

*/
type DeleteStudentsID struct {
	Context *middleware.Context
	Handler DeleteStudentsIDHandler
}

func (o *DeleteStudentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteStudentsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
