// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetStudentsIDOKCode is the HTTP code returned for type GetStudentsIDOK
const GetStudentsIDOKCode int = 200

/*GetStudentsIDOK Student response

swagger:response getStudentsIdOK
*/
type GetStudentsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Student `json:"body,omitempty"`
}

// NewGetStudentsIDOK creates GetStudentsIDOK with default headers values
func NewGetStudentsIDOK() *GetStudentsIDOK {

	return &GetStudentsIDOK{}
}

// WithPayload adds the payload to the get students Id o k response
func (o *GetStudentsIDOK) WithPayload(payload *models.Student) *GetStudentsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get students Id o k response
func (o *GetStudentsIDOK) SetPayload(payload *models.Student) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStudentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStudentsIDDefault Unexpected error

swagger:response getStudentsIdDefault
*/
type GetStudentsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStudentsIDDefault creates GetStudentsIDDefault with default headers values
func NewGetStudentsIDDefault(code int) *GetStudentsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStudentsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get students ID default response
func (o *GetStudentsIDDefault) WithStatusCode(code int) *GetStudentsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get students ID default response
func (o *GetStudentsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get students ID default response
func (o *GetStudentsIDDefault) WithPayload(payload *models.Error) *GetStudentsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get students ID default response
func (o *GetStudentsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStudentsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
