// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetStudentsOKCode is the HTTP code returned for type GetStudentsOK
const GetStudentsOKCode int = 200

/*GetStudentsOK A array of User objects

swagger:response getStudentsOK
*/
type GetStudentsOK struct {

	/*
	  In: Body
	*/
	Payload *GetStudentsOKBody `json:"body,omitempty"`
}

// NewGetStudentsOK creates GetStudentsOK with default headers values
func NewGetStudentsOK() *GetStudentsOK {

	return &GetStudentsOK{}
}

// WithPayload adds the payload to the get students o k response
func (o *GetStudentsOK) WithPayload(payload *GetStudentsOKBody) *GetStudentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get students o k response
func (o *GetStudentsOK) SetPayload(payload *GetStudentsOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStudentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetStudentsDefault Unexpected error

swagger:response getStudentsDefault
*/
type GetStudentsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStudentsDefault creates GetStudentsDefault with default headers values
func NewGetStudentsDefault(code int) *GetStudentsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStudentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get students default response
func (o *GetStudentsDefault) WithStatusCode(code int) *GetStudentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get students default response
func (o *GetStudentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get students default response
func (o *GetStudentsDefault) WithPayload(payload *models.Error) *GetStudentsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get students default response
func (o *GetStudentsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStudentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
