// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PatchStudentsIDOKCode is the HTTP code returned for type PatchStudentsIDOK
const PatchStudentsIDOKCode int = 200

/*PatchStudentsIDOK Updated student response

swagger:response patchStudentsIdOK
*/
type PatchStudentsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Student `json:"body,omitempty"`
}

// NewPatchStudentsIDOK creates PatchStudentsIDOK with default headers values
func NewPatchStudentsIDOK() *PatchStudentsIDOK {

	return &PatchStudentsIDOK{}
}

// WithPayload adds the payload to the patch students Id o k response
func (o *PatchStudentsIDOK) WithPayload(payload *models.Student) *PatchStudentsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch students Id o k response
func (o *PatchStudentsIDOK) SetPayload(payload *models.Student) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchStudentsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchStudentsIDDefault Unexpected error

swagger:response patchStudentsIdDefault
*/
type PatchStudentsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchStudentsIDDefault creates PatchStudentsIDDefault with default headers values
func NewPatchStudentsIDDefault(code int) *PatchStudentsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchStudentsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch students ID default response
func (o *PatchStudentsIDDefault) WithStatusCode(code int) *PatchStudentsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch students ID default response
func (o *PatchStudentsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch students ID default response
func (o *PatchStudentsIDDefault) WithPayload(payload *models.Error) *PatchStudentsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch students ID default response
func (o *PatchStudentsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchStudentsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
