// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostStudentsHandlerFunc turns a function with the right signature into a post students handler
type PostStudentsHandlerFunc func(PostStudentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostStudentsHandlerFunc) Handle(params PostStudentsParams) middleware.Responder {
	return fn(params)
}

// PostStudentsHandler interface for that can handle valid post students params
type PostStudentsHandler interface {
	Handle(PostStudentsParams) middleware.Responder
}

// NewPostStudents creates a new http.Handler for the post students operation
func NewPostStudents(ctx *middleware.Context, handler PostStudentsHandler) *PostStudents {
	return &PostStudents{Context: ctx, Handler: handler}
}

/*PostStudents swagger:route POST /students postStudents

Create a new student

*/
type PostStudents struct {
	Context *middleware.Context
	Handler PostStudentsHandler
}

func (o *PostStudents) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostStudentsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
