// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PostStudentsCreatedCode is the HTTP code returned for type PostStudentsCreated
const PostStudentsCreatedCode int = 201

/*PostStudentsCreated Student successfully created

swagger:response postStudentsCreated
*/
type PostStudentsCreated struct {
}

// NewPostStudentsCreated creates PostStudentsCreated with default headers values
func NewPostStudentsCreated() *PostStudentsCreated {

	return &PostStudentsCreated{}
}

// WriteResponse to the client
func (o *PostStudentsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*PostStudentsDefault Unexpected error

swagger:response postStudentsDefault
*/
type PostStudentsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostStudentsDefault creates PostStudentsDefault with default headers values
func NewPostStudentsDefault(code int) *PostStudentsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostStudentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post students default response
func (o *PostStudentsDefault) WithStatusCode(code int) *PostStudentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post students default response
func (o *PostStudentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post students default response
func (o *PostStudentsDefault) WithPayload(payload *models.Error) *PostStudentsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post students default response
func (o *PostStudentsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostStudentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
