// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"signin2/restapi/operations/meetings"
	"signin2/restapi/operations/people"
	"signin2/restapi/operations/teams"
)

// NewSignInTrackerAPI creates a new SignInTracker instance
func NewSignInTrackerAPI(spec *loads.Document) *SignInTrackerAPI {
	return &SignInTrackerAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		MeetingsDeleteMeetingsIDHandler: meetings.DeleteMeetingsIDHandlerFunc(func(params meetings.DeleteMeetingsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation MeetingsDeleteMeetingsID has not yet been implemented")
		}),
		PeopleDeletePeopleIDHandler: people.DeletePeopleIDHandlerFunc(func(params people.DeletePeopleIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PeopleDeletePeopleID has not yet been implemented")
		}),
		TeamsDeleteTeamsIDHandler: teams.DeleteTeamsIDHandlerFunc(func(params teams.DeleteTeamsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation TeamsDeleteTeamsID has not yet been implemented")
		}),
		MeetingsGetMeetingsHandler: meetings.GetMeetingsHandlerFunc(func(params meetings.GetMeetingsParams) middleware.Responder {
			return middleware.NotImplemented("operation MeetingsGetMeetings has not yet been implemented")
		}),
		MeetingsGetMeetingsIDHandler: meetings.GetMeetingsIDHandlerFunc(func(params meetings.GetMeetingsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation MeetingsGetMeetingsID has not yet been implemented")
		}),
		PeopleGetPeopleHandler: people.GetPeopleHandlerFunc(func(params people.GetPeopleParams) middleware.Responder {
			return middleware.NotImplemented("operation PeopleGetPeople has not yet been implemented")
		}),
		PeopleGetPeopleIDHandler: people.GetPeopleIDHandlerFunc(func(params people.GetPeopleIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PeopleGetPeopleID has not yet been implemented")
		}),
		TeamsGetTeamsHandler: teams.GetTeamsHandlerFunc(func(params teams.GetTeamsParams) middleware.Responder {
			return middleware.NotImplemented("operation TeamsGetTeams has not yet been implemented")
		}),
		TeamsGetTeamsIDHandler: teams.GetTeamsIDHandlerFunc(func(params teams.GetTeamsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation TeamsGetTeamsID has not yet been implemented")
		}),
		MeetingsPatchMeetingsIDHandler: meetings.PatchMeetingsIDHandlerFunc(func(params meetings.PatchMeetingsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation MeetingsPatchMeetingsID has not yet been implemented")
		}),
		PeoplePatchPeopleIDHandler: people.PatchPeopleIDHandlerFunc(func(params people.PatchPeopleIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PeoplePatchPeopleID has not yet been implemented")
		}),
		TeamsPatchTeamsIDHandler: teams.PatchTeamsIDHandlerFunc(func(params teams.PatchTeamsIDParams) middleware.Responder {
			return middleware.NotImplemented("operation TeamsPatchTeamsID has not yet been implemented")
		}),
		MeetingsPostMeetingsHandler: meetings.PostMeetingsHandlerFunc(func(params meetings.PostMeetingsParams) middleware.Responder {
			return middleware.NotImplemented("operation MeetingsPostMeetings has not yet been implemented")
		}),
		PeoplePostPeopleHandler: people.PostPeopleHandlerFunc(func(params people.PostPeopleParams) middleware.Responder {
			return middleware.NotImplemented("operation PeoplePostPeople has not yet been implemented")
		}),
		TeamsPostTeamsHandler: teams.PostTeamsHandlerFunc(func(params teams.PostTeamsParams) middleware.Responder {
			return middleware.NotImplemented("operation TeamsPostTeams has not yet been implemented")
		}),
	}
}

/*SignInTrackerAPI the sign in tracker API */
type SignInTrackerAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// MeetingsDeleteMeetingsIDHandler sets the operation handler for the delete meetings ID operation
	MeetingsDeleteMeetingsIDHandler meetings.DeleteMeetingsIDHandler
	// PeopleDeletePeopleIDHandler sets the operation handler for the delete people ID operation
	PeopleDeletePeopleIDHandler people.DeletePeopleIDHandler
	// TeamsDeleteTeamsIDHandler sets the operation handler for the delete teams ID operation
	TeamsDeleteTeamsIDHandler teams.DeleteTeamsIDHandler
	// MeetingsGetMeetingsHandler sets the operation handler for the get meetings operation
	MeetingsGetMeetingsHandler meetings.GetMeetingsHandler
	// MeetingsGetMeetingsIDHandler sets the operation handler for the get meetings ID operation
	MeetingsGetMeetingsIDHandler meetings.GetMeetingsIDHandler
	// PeopleGetPeopleHandler sets the operation handler for the get people operation
	PeopleGetPeopleHandler people.GetPeopleHandler
	// PeopleGetPeopleIDHandler sets the operation handler for the get people ID operation
	PeopleGetPeopleIDHandler people.GetPeopleIDHandler
	// TeamsGetTeamsHandler sets the operation handler for the get teams operation
	TeamsGetTeamsHandler teams.GetTeamsHandler
	// TeamsGetTeamsIDHandler sets the operation handler for the get teams ID operation
	TeamsGetTeamsIDHandler teams.GetTeamsIDHandler
	// MeetingsPatchMeetingsIDHandler sets the operation handler for the patch meetings ID operation
	MeetingsPatchMeetingsIDHandler meetings.PatchMeetingsIDHandler
	// PeoplePatchPeopleIDHandler sets the operation handler for the patch people ID operation
	PeoplePatchPeopleIDHandler people.PatchPeopleIDHandler
	// TeamsPatchTeamsIDHandler sets the operation handler for the patch teams ID operation
	TeamsPatchTeamsIDHandler teams.PatchTeamsIDHandler
	// MeetingsPostMeetingsHandler sets the operation handler for the post meetings operation
	MeetingsPostMeetingsHandler meetings.PostMeetingsHandler
	// PeoplePostPeopleHandler sets the operation handler for the post people operation
	PeoplePostPeopleHandler people.PostPeopleHandler
	// TeamsPostTeamsHandler sets the operation handler for the post teams operation
	TeamsPostTeamsHandler teams.PostTeamsHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *SignInTrackerAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *SignInTrackerAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *SignInTrackerAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *SignInTrackerAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *SignInTrackerAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *SignInTrackerAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *SignInTrackerAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the SignInTrackerAPI
func (o *SignInTrackerAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.MeetingsDeleteMeetingsIDHandler == nil {
		unregistered = append(unregistered, "meetings.DeleteMeetingsIDHandler")
	}

	if o.PeopleDeletePeopleIDHandler == nil {
		unregistered = append(unregistered, "people.DeletePeopleIDHandler")
	}

	if o.TeamsDeleteTeamsIDHandler == nil {
		unregistered = append(unregistered, "teams.DeleteTeamsIDHandler")
	}

	if o.MeetingsGetMeetingsHandler == nil {
		unregistered = append(unregistered, "meetings.GetMeetingsHandler")
	}

	if o.MeetingsGetMeetingsIDHandler == nil {
		unregistered = append(unregistered, "meetings.GetMeetingsIDHandler")
	}

	if o.PeopleGetPeopleHandler == nil {
		unregistered = append(unregistered, "people.GetPeopleHandler")
	}

	if o.PeopleGetPeopleIDHandler == nil {
		unregistered = append(unregistered, "people.GetPeopleIDHandler")
	}

	if o.TeamsGetTeamsHandler == nil {
		unregistered = append(unregistered, "teams.GetTeamsHandler")
	}

	if o.TeamsGetTeamsIDHandler == nil {
		unregistered = append(unregistered, "teams.GetTeamsIDHandler")
	}

	if o.MeetingsPatchMeetingsIDHandler == nil {
		unregistered = append(unregistered, "meetings.PatchMeetingsIDHandler")
	}

	if o.PeoplePatchPeopleIDHandler == nil {
		unregistered = append(unregistered, "people.PatchPeopleIDHandler")
	}

	if o.TeamsPatchTeamsIDHandler == nil {
		unregistered = append(unregistered, "teams.PatchTeamsIDHandler")
	}

	if o.MeetingsPostMeetingsHandler == nil {
		unregistered = append(unregistered, "meetings.PostMeetingsHandler")
	}

	if o.PeoplePostPeopleHandler == nil {
		unregistered = append(unregistered, "people.PostPeopleHandler")
	}

	if o.TeamsPostTeamsHandler == nil {
		unregistered = append(unregistered, "teams.PostTeamsHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *SignInTrackerAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *SignInTrackerAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *SignInTrackerAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *SignInTrackerAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *SignInTrackerAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *SignInTrackerAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the sign in tracker API
func (o *SignInTrackerAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *SignInTrackerAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/meetings/{id}"] = meetings.NewDeleteMeetingsID(o.context, o.MeetingsDeleteMeetingsIDHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/people/{id}"] = people.NewDeletePeopleID(o.context, o.PeopleDeletePeopleIDHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/teams/{id}"] = teams.NewDeleteTeamsID(o.context, o.TeamsDeleteTeamsIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/meetings"] = meetings.NewGetMeetings(o.context, o.MeetingsGetMeetingsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/meetings/{id}"] = meetings.NewGetMeetingsID(o.context, o.MeetingsGetMeetingsIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/people"] = people.NewGetPeople(o.context, o.PeopleGetPeopleHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/people/{id}"] = people.NewGetPeopleID(o.context, o.PeopleGetPeopleIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams"] = teams.NewGetTeams(o.context, o.TeamsGetTeamsHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams/{id}"] = teams.NewGetTeamsID(o.context, o.TeamsGetTeamsIDHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/meetings/{id}"] = meetings.NewPatchMeetingsID(o.context, o.MeetingsPatchMeetingsIDHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/people/{id}"] = people.NewPatchPeopleID(o.context, o.PeoplePatchPeopleIDHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/teams/{id}"] = teams.NewPatchTeamsID(o.context, o.TeamsPatchTeamsIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/meetings"] = meetings.NewPostMeetings(o.context, o.MeetingsPostMeetingsHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/people"] = people.NewPostPeople(o.context, o.PeoplePostPeopleHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/teams"] = teams.NewPostTeams(o.context, o.TeamsPostTeamsHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *SignInTrackerAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *SignInTrackerAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *SignInTrackerAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *SignInTrackerAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
