// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// DeleteTeamsIDNoContentCode is the HTTP code returned for type DeleteTeamsIDNoContent
const DeleteTeamsIDNoContentCode int = 204

/*DeleteTeamsIDNoContent Representation of the Team that was just deleted.

swagger:response deleteTeamsIdNoContent
*/
type DeleteTeamsIDNoContent struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewDeleteTeamsIDNoContent creates DeleteTeamsIDNoContent with default headers values
func NewDeleteTeamsIDNoContent() *DeleteTeamsIDNoContent {

	return &DeleteTeamsIDNoContent{}
}

// WithPayload adds the payload to the delete teams Id no content response
func (o *DeleteTeamsIDNoContent) WithPayload(payload *models.Team) *DeleteTeamsIDNoContent {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete teams Id no content response
func (o *DeleteTeamsIDNoContent) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamsIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(204)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*DeleteTeamsIDDefault Unexpected error

swagger:response deleteTeamsIdDefault
*/
type DeleteTeamsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteTeamsIDDefault creates DeleteTeamsIDDefault with default headers values
func NewDeleteTeamsIDDefault(code int) *DeleteTeamsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTeamsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete teams ID default response
func (o *DeleteTeamsIDDefault) WithStatusCode(code int) *DeleteTeamsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete teams ID default response
func (o *DeleteTeamsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete teams ID default response
func (o *DeleteTeamsIDDefault) WithPayload(payload *models.Error) *DeleteTeamsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete teams ID default response
func (o *DeleteTeamsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
