// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteTeamsIDHandlerFunc turns a function with the right signature into a delete teams ID handler
type DeleteTeamsIDHandlerFunc func(DeleteTeamsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteTeamsIDHandlerFunc) Handle(params DeleteTeamsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteTeamsIDHandler interface for that can handle valid delete teams ID params
type DeleteTeamsIDHandler interface {
	Handle(DeleteTeamsIDParams) middleware.Responder
}

// NewDeleteTeamsID creates a new http.Handler for the delete teams ID operation
func NewDeleteTeamsID(ctx *middleware.Context, handler DeleteTeamsIDHandler) *DeleteTeamsID {
	return &DeleteTeamsID{Context: ctx, Handler: handler}
}

/*DeleteTeamsID swagger:route DELETE /teams/{id} Teams deleteTeamsId

Delete the Team with the given ID

*/
type DeleteTeamsID struct {
	Context *middleware.Context
	Handler DeleteTeamsIDHandler
}

func (o *DeleteTeamsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteTeamsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
