// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// GetTeamsIDOKCode is the HTTP code returned for type GetTeamsIDOK
const GetTeamsIDOKCode int = 200

/*GetTeamsIDOK Team response

swagger:response getTeamsIdOK
*/
type GetTeamsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewGetTeamsIDOK creates GetTeamsIDOK with default headers values
func NewGetTeamsIDOK() *GetTeamsIDOK {

	return &GetTeamsIDOK{}
}

// WithPayload adds the payload to the get teams Id o k response
func (o *GetTeamsIDOK) WithPayload(payload *models.Team) *GetTeamsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams Id o k response
func (o *GetTeamsIDOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamsIDDefault Unexpected error

swagger:response getTeamsIdDefault
*/
type GetTeamsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamsIDDefault creates GetTeamsIDDefault with default headers values
func NewGetTeamsIDDefault(code int) *GetTeamsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get teams ID default response
func (o *GetTeamsIDDefault) WithStatusCode(code int) *GetTeamsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get teams ID default response
func (o *GetTeamsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get teams ID default response
func (o *GetTeamsIDDefault) WithPayload(payload *models.Error) *GetTeamsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams ID default response
func (o *GetTeamsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
