// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PatchTeamsIDHandlerFunc turns a function with the right signature into a patch teams ID handler
type PatchTeamsIDHandlerFunc func(PatchTeamsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchTeamsIDHandlerFunc) Handle(params PatchTeamsIDParams) middleware.Responder {
	return fn(params)
}

// PatchTeamsIDHandler interface for that can handle valid patch teams ID params
type PatchTeamsIDHandler interface {
	Handle(PatchTeamsIDParams) middleware.Responder
}

// NewPatchTeamsID creates a new http.Handler for the patch teams ID operation
func NewPatchTeamsID(ctx *middleware.Context, handler PatchTeamsIDHandler) *PatchTeamsID {
	return &PatchTeamsID{Context: ctx, Handler: handler}
}

/*PatchTeamsID swagger:route PATCH /teams/{id} Teams patchTeamsId

Update a particular Team

*/
type PatchTeamsID struct {
	Context *middleware.Context
	Handler PatchTeamsIDHandler
}

func (o *PatchTeamsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchTeamsIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
