// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PatchTeamsIDOKCode is the HTTP code returned for type PatchTeamsIDOK
const PatchTeamsIDOKCode int = 200

/*PatchTeamsIDOK Updated Team response

swagger:response patchTeamsIdOK
*/
type PatchTeamsIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewPatchTeamsIDOK creates PatchTeamsIDOK with default headers values
func NewPatchTeamsIDOK() *PatchTeamsIDOK {

	return &PatchTeamsIDOK{}
}

// WithPayload adds the payload to the patch teams Id o k response
func (o *PatchTeamsIDOK) WithPayload(payload *models.Team) *PatchTeamsIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch teams Id o k response
func (o *PatchTeamsIDOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchTeamsIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PatchTeamsIDDefault Unexpected error

swagger:response patchTeamsIdDefault
*/
type PatchTeamsIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchTeamsIDDefault creates PatchTeamsIDDefault with default headers values
func NewPatchTeamsIDDefault(code int) *PatchTeamsIDDefault {
	if code <= 0 {
		code = 500
	}

	return &PatchTeamsIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the patch teams ID default response
func (o *PatchTeamsIDDefault) WithStatusCode(code int) *PatchTeamsIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the patch teams ID default response
func (o *PatchTeamsIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the patch teams ID default response
func (o *PatchTeamsIDDefault) WithPayload(payload *models.Error) *PatchTeamsIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch teams ID default response
func (o *PatchTeamsIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchTeamsIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
