// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "signin2/models"
)

// PostTeamsCreatedCode is the HTTP code returned for type PostTeamsCreated
const PostTeamsCreatedCode int = 201

/*PostTeamsCreated Team successfully created

swagger:response postTeamsCreated
*/
type PostTeamsCreated struct {
}

// NewPostTeamsCreated creates PostTeamsCreated with default headers values
func NewPostTeamsCreated() *PostTeamsCreated {

	return &PostTeamsCreated{}
}

// WriteResponse to the client
func (o *PostTeamsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*PostTeamsDefault Unexpected error

swagger:response postTeamsDefault
*/
type PostTeamsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostTeamsDefault creates PostTeamsDefault with default headers values
func NewPostTeamsDefault(code int) *PostTeamsDefault {
	if code <= 0 {
		code = 500
	}

	return &PostTeamsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post teams default response
func (o *PostTeamsDefault) WithStatusCode(code int) *PostTeamsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post teams default response
func (o *PostTeamsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post teams default response
func (o *PostTeamsDefault) WithPayload(payload *models.Error) *PostTeamsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post teams default response
func (o *PostTeamsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostTeamsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
