// Code generated by go-swagger; DO NOT EDIT.

package teams

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostTeamsHandlerFunc turns a function with the right signature into a post teams handler
type PostTeamsHandlerFunc func(PostTeamsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostTeamsHandlerFunc) Handle(params PostTeamsParams) middleware.Responder {
	return fn(params)
}

// PostTeamsHandler interface for that can handle valid post teams params
type PostTeamsHandler interface {
	Handle(PostTeamsParams) middleware.Responder
}

// NewPostTeams creates a new http.Handler for the post teams operation
func NewPostTeams(ctx *middleware.Context, handler PostTeamsHandler) *PostTeams {
	return &PostTeams{Context: ctx, Handler: handler}
}

/*PostTeams swagger:route POST /teams Teams postTeams

Create a new team

*/
type PostTeams struct {
	Context *middleware.Context
	Handler PostTeamsHandler
}

func (o *PostTeams) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostTeamsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
