// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Count The number of items in a collection.
// swagger:model count
type Count int64

// Validate validates this count
func (m Count) Validate(formats strfmt.Registry) error {
	return nil
}
