// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Time time
// swagger:model Time
type Time struct {

	// hour
	// Required: true
	// Maximum: 24
	// Minimum: 0
	Hour *int64 `json:"Hour"`

	// minute
	// Required: true
	// Maximum: 59
	// Minimum: 0
	Minute *int64 `json:"Minute"`
}

// Validate validates this time
func (m *Time) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHour(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinute(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Time) validateHour(formats strfmt.Registry) error {

	if err := validate.Required("Hour", "body", m.Hour); err != nil {
		return err
	}

	if err := validate.MinimumInt("Hour", "body", int64(*m.Hour), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("Hour", "body", int64(*m.Hour), 24, false); err != nil {
		return err
	}

	return nil
}

func (m *Time) validateMinute(formats strfmt.Registry) error {

	if err := validate.Required("Minute", "body", m.Minute); err != nil {
		return err
	}

	if err := validate.MinimumInt("Minute", "body", int64(*m.Minute), 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("Minute", "body", int64(*m.Minute), 59, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Time) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Time) UnmarshalBinary(b []byte) error {
	var res Time
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
