// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sign In tracker API

    Schemes:
      http
      https
    Host: virtserver.swaggerhub.com
    BasePath: /kennedyrobotics/SignIn/1.0.0
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
