// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sign In tracker API

    Schemes:
      http
    Host: api.example.com
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
